version: "3.5"

networks:
  laravel:

services:
  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_module
    ports:
      - 3000:3000
    command: npm run dev
    environment:
      CHOKIDAR_USEPOLLING: "true"
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./backend:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: lara_db
      MYSQL_USER: lara_user
      MYSQL_PASSWORD: "1234"
      MYSQL_ROOT_PASSWORD: "1234"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
  php:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: php
    volumes:
      - ./backend:/var/www
    ports:
      - 9000:9000
    networks:
      - laravel
